runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /.*
  script: pubsub_publisher.app

#builtins:
#- appstats: on

env_variables:
  PROJECT: 'setindeploy'
  TOPIC: 'setindeploy'
  








